package ru.mos.emias.notifications.v1.subscription.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import ru.mos.emias.notifications.v1.subscription.SubscriptionServicePortType;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-12T17:53:39.534+03:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "SubscriptionService",
                  wsdlLocation = "file:src/main/resources/subscriptionService.wsdl",
                  targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/soap/")
public class SubscriptionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://emias.mos.ru/notifications/v1/subscription/soap/", "SubscriptionService");
    public final static QName SubscriptionService = new QName("http://emias.mos.ru/notifications/v1/subscription/soap/", "SubscriptionService");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/subscriptionService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SubscriptionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/subscriptionService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SubscriptionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubscriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SubscriptionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SubscriptionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SubscriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SubscriptionServicePortType
     */
    @WebEndpoint(name = "SubscriptionService")
    public SubscriptionServicePortType getSubscriptionService() {
        return super.getPort(SubscriptionService, SubscriptionServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionServicePortType
     */
    @WebEndpoint(name = "SubscriptionService")
    public SubscriptionServicePortType getSubscriptionService(WebServiceFeature... features) {
        return super.getPort(SubscriptionService, SubscriptionServicePortType.class, features);
    }

}
