package ru.mos.emias.notifications.v1.subscription;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-12T17:53:39.507+03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/", name = "SubscriptionServicePortType")
@XmlSeeAlso({ru.mos.emias.system.v1.faults.ObjectFactory.class, ObjectFactory.class, ru.mos.emias.notifications.v1.subscription.application.ObjectFactory.class, generated.ObjectFactory.class, ru.mos.emias.system.v1.usercontext.ObjectFactory.class, ru.mos.emias.notifications.v1.subscription.types.ObjectFactory.class, ru.mos.emias.notifications.v1.common.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SubscriptionServicePortType {

    /**
     * Список подписок пациента
     *                 
     */
    @WebMethod(action = "getSubscriptions")
    @WebResult(name = "GetSubscriptionsResponse", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/", partName = "body")
    public GetSubscriptionsResponse getSubscriptions(

        @WebParam(partName = "body", name = "GetSubscriptionsRequest", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/")
        GetSubscriptionsRequest body
    ) throws Fault;

    /**
     * Список типов подписок
     *                 
     */
    @WebMethod(action = "getSubscriptionTypes")
    @WebResult(name = "GetSubscriptionTypesResponse", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/", partName = "body")
    public GetSubscriptionTypesResponse getSubscriptionTypes(

        @WebParam(partName = "body", name = "GetSubscriptionTypesRequest", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/")
        GetSubscriptionTypesRequest body
    ) throws Fault;

    /**
     * Список подписок заяителя
     *                 
     */
    @WebMethod(action = "getApplicantSubscriptions")
    @WebResult(name = "GetApplicantSubscriptionsResponse", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/", partName = "body")
    public GetApplicantSubscriptionsResponse getApplicantSubscriptions(

        @WebParam(partName = "body", name = "GetApplicantSubscriptionsRequest", targetNamespace = "http://emias.mos.ru/notifications/v1/subscription/")
        GetApplicantSubscriptionsRequest body
    ) throws Fault;
}
